services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gnec

networks:
  gnec:
    driver: bridge

volumes:
  postgres_data: